name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31
        with:
          extra_nix_config: |
            extra-substituters = https://cache.iog.io https://purescript-lua.cachix.org
            extra-trusted-public-keys = hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= purescript-lua.cachix.org-1:yLs4ei2HtnuPtzLekOrW3xdfm95+Etw15gwgyIGTayA=

      - name: Build
        run: nix develop -c ./scripts/build

      - name: Test
        run: if [ -f scripts/test ]; then nix develop -c bash ./scripts/test; fi

      - name: Luacheck
        run: nix develop -c luacheck --quiet --std lua51 --no-unused-args --max-line-length 130 src/

      - name: Format check
        run: nix fmt && git diff --exit-code
